# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    url: /archives
    text: 归档
  tags:
    url: /tags
    text: 标签
  th-list:
    text: 分类
    url: /categories
  send-o:
    text: 留言
    url: /messages
  smile-o:
    text: 关于
    url: /about

menu2:
  github:
    text: github
    url: https://github.com/JinmaQAQ
    target: _blank
  rss:
    text: Rss
    url: atom.xml
    target: _blank
  envelope-o:
    text: 邮箱
    url: mailto:jinmaup@gmail.com
  stack-overflow:
    text: 掘金
    url: https://juejin.im/user/599b6d255188252447222dfd
    target: _blank
  facebook:
    text: facebook
    url: https://www.facebook.com/profile.php?id=100022718221060
    target: _blank
  weixin:
    text: 微信
    url: img/weixin.gif
    target: _blank



# 你的头像url
avatar: /img/avatar.jpg
# avatar link
avatar_link: /
# 头像背景图
brand: /img/2510-5.jpg
# favicon
favicon: /img/favicon.ico

# email
email: 少年锦时.

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: 标签
archives_title: 归档
categories_title: 分类

# 文章截断
excerpt_render: true
excerpt_length: 175
excerpt_link: 阅读全文...
mathjax: false
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: false

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 感谢您的鼓励支持！
  wechat: /img/wechat.png     #微信，关闭设为 false
  alipay: /img/alipay.png     #支付宝，关闭设为 false
  wechatalipay: /img/dog.png

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: false

# 是否开启toc
# toc: true
toc:
  list_number: true  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 文章标题：  <a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.title %></a><br>创建时间：  <%- date(page.date) %><br>更新时间：  <%- date(page.updated) %>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: false

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 是否开启友言评论, 填写友言用户id2146950
uyan_uid: false

# 是否使用 gitment，https://github.com/imsun/gitment
gitment:
  owner: JinmaQAQ
  repo: JinmaQAQ.github.io
  client_id: 57b2bf7c5af44e329e4b
  client_secret: 47a4a9026c7f22e4a4fc916c962248d73ed492e0

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2017

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 业精于勤荒于嬉，行成于思毁于随。

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_pv: 访问次数：
  site_uv: 访问用户：

# 动态定义title
title_change:
  normal: (つェ⊂)咦!又好了!
  leave: 死鬼去哪里了！

# 设置为 true 发布后将使用 unpkg cdn
cdn: false

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: 京ICP备1234556号-1
